### ISSUE TITLE
PLUMED software help

### ISSUE THREAD

**Issue by YangHang-021** [jianjiang12/MLP-for-2D-ices#1]
I'm very sorry to have disturbed you，i am a graduate student majoring in condensed matter. I have recently read your papers entitled "Rich proton dynamics and phase behaviours of nanoconfined ices" and "First-Principles Molecular ices". Recently, I have been reading your articles entitled "Rich proton dynamics and phase behaviours of nanoconfined ices" and "First-Principles Molecular Dynamics Simulations of the Spontaneous Freezing Transition of 2D Water in a Nanoslit", in which you used PLUMED software to introduce the upper and lower virtual walls to confine the water molecules. In my project, I would also like to utilize such constraints in combination with CP2K software. Therefore, I would like to ask you here for specific inputs for the relevant plumed.dat! In particular, can you send me a copy of the original input file for the plumed.dat file in the first article? I would be very grateful if you could reply!

**Comment by jianjiang12** [comment]
I have upload the script for setting up a wall using PLUMED. Please check the lastest commit and the directory: Scripts/Plumed to set up a wall
